swagger: "2.0"

info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0

paths:
  /shorter/{url}:
    post:
      summary: Creates a shorted url from another one
      description: Optional extended description in Markdown.
      parameters:
        - in: path
          name: url
          required: true
          type: string
          description: long url
      responses:
        200:
          description: OK
  /shorter/{id}:
    get:
      summary: Creates a shorted url from another one
      description: Optional extended description in Markdown.
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: long url
      responses:
        200:
          description: OK

