swagger: "2.0"

info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0

paths:
  /shorter/{url}:
    post:
      summary: Creates a shorted url from a big one (exires in 1 day)
      description: this API creates a shorted link to your long link
      parameters:
        - in: path
          name: url
          required: true
          type: string
          description: long
      responses:
        200:
          description: OK
  /shorter/{id}:
    get:
      summary: redirects the page to the log link
      description: takes short link id and redirects the page to the main link
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: long url
      responses:
        200:
          description: OK

